name: Add a new page

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL'
        required: true

jobs:
  add:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          go run ./cmd/add ${{ github.event.inputs.url }}
